### ISSUE TITLE
compare multiple OTU tables from different treatments to a control treatment

### ISSUE THREAD

**Issue by Jigyasa3** [ncchung/jaccard#1]
Hi @ncchung!

Thank you for an interesting package! I am interested in measuring the similarity between multiple presence-absence OTU tables across treatments. The example on the website [https://nnnn.shinyapps.io/jaccard/](url) shows how to compute statistical significance among sites/samples on a single OTU table. Is it possible to compare multiple OTU tables from different treatments to a control treatment, and examine if they are more similar to a control treatment than expected?

**Comment by ncchung** [comment]
Hi, two vectors of binary data can be compared. Thus, one vector of a control (for example, placebo treatment on multiple bioregions) and another vector of a case (for example, treatment of interest on multiple bioregions) can be evaluated and tested using this package.

If you are using the Shiny web app, it's a matter of formatting two CSV files appropriately. For more flexibility, I'd recommend you to use a R package.
